drop user job;
CREATE USER job IDENTIFIED BY job
 DEFAULT TABLESPACE USERS
 TEMPORARY TABLESPACE TEMP
 PROFILE "DEFAULT"
 QUOTA UNLIMITED ON USERS;

GRANT "CONNECT" TO job;
GRANT "RESOURCE" TO job;
ALTER USER job DEFAULT ROLE "CONNECT", "RESOURCE";
